package com.ssm.one.dao.main;

import java.util.List;

import com.ssm.one.entity.main.SnBsbi;

public interface SnBsbiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SN_BSBI
     *
     * @mbggenerated Fri Dec 13 14:17:51 CST 2019
     */
    int insert(SnBsbi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SN_BSBI
     *
     * @mbggenerated Fri Dec 13 14:17:51 CST 2019
     */
    int insertSelective(SnBsbi record);

	List<SnBsbi> selectSnbsbis();
}