package com.ssm.one.entity.main;

public class SnBsbi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SN_BSBI.BSCD
     *
     * @mbggenerated Mon Dec 16 11:58:11 GMT+08:00 2019
     */
    private String bscd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SN_BSBI.BSNM
     *
     * @mbggenerated Mon Dec 16 11:58:11 GMT+08:00 2019
     */
    private String bsnm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SN_BSBI.BSCD
     *
     * @return the value of SN_BSBI.BSCD
     *
     * @mbggenerated Mon Dec 16 11:58:11 GMT+08:00 2019
     */
    public String getBscd() {
        return bscd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SN_BSBI.BSCD
     *
     * @param bscd the value for SN_BSBI.BSCD
     *
     * @mbggenerated Mon Dec 16 11:58:11 GMT+08:00 2019
     */
    public void setBscd(String bscd) {
        this.bscd = bscd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SN_BSBI.BSNM
     *
     * @return the value of SN_BSBI.BSNM
     *
     * @mbggenerated Mon Dec 16 11:58:11 GMT+08:00 2019
     */
    public String getBsnm() {
        return bsnm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SN_BSBI.BSNM
     *
     * @param bsnm the value for SN_BSBI.BSNM
     *
     * @mbggenerated Mon Dec 16 11:58:11 GMT+08:00 2019
     */
    public void setBsnm(String bsnm) {
        this.bsnm = bsnm;
    }
}