package com.demo.giao_one.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.expired
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    private Integer expired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.disabled
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    private Integer disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.createdate
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.expired
     *
     * @return the value of user.expired
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    public Integer getExpired() {
        return expired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.expired
     *
     * @param expired the value for user.expired
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    public void setExpired(Integer expired) {
        this.expired = expired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.disabled
     *
     * @return the value of user.disabled
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    public Integer getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.disabled
     *
     * @param disabled the value for user.disabled
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    public void setDisabled(Integer disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.createdate
     *
     * @return the value of user.createdate
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.createdate
     *
     * @param createdate the value for user.createdate
     *
     * @mbggenerated Thu Dec 24 14:29:09 CST 2020
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}